package com.vijayanix.iot.common.log;


import com.vijayanix.iot.action.device.common.ActionDeviceSynchronizeInterentDiscoverLocal;
import com.vijayanix.iot.command.device.watchman.CommandWatchmanGetStatusLocal;
import com.vijayanix.iot.command.device.watchman.CommandWatchmanPostStatusLocal;
import com.vijayanix.iot.common.net.proxy.MeshLog;
import com.vijayanix.iot.common.net.rest2.HttpUtil;
import com.vijayanix.iot.mqtt.ActionListener;
import com.vijayanix.iot.mqtt.Mqtt;
import com.vijayanix.iot.mqtt.MqttCallbackHandler;
import com.vijayanix.iot.ui.main.MainActivity;
import com.vijayanix.iot.util.UtilsUI;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;


// it is generated by python
public class InitLogger {
    public static void init(){
        //######content######
        //ConfigureLog4J.configure();
        MeshLog.initLog4jLevel(Level.DEBUG);
        Logger.getLogger(MainActivity.class).setLevel(Level.DEBUG);
        Logger.getLogger(ActionDeviceSynchronizeInterentDiscoverLocal.class).setLevel(Level.DEBUG);
        Logger.getLogger(UtilsUI.class).setLevel(Level.DEBUG);
        Logger.getLogger(ActionListener.class).setLevel(Level.DEBUG);
        Logger.getLogger(Mqtt.class).setLevel(Level.DEBUG);
        Logger.getLogger(MqttCallbackHandler.class).setLevel(Level.DEBUG);
        Logger.getLogger(HttpUtil.class).setLevel(Level.DEBUG);
        Logger.getLogger(CommandWatchmanGetStatusLocal.class).setLevel(Level.DEBUG);
        Logger.getLogger(CommandWatchmanPostStatusLocal.class).setLevel(Level.DEBUG);


    }
}